name: CD using Docker Image

on:
    pull_request:
    push:
        branches:
          - 'master'
        paths:
          - .github/workflows/CICD.yml
          - tee2/**

env:
    IMAGE: ${{ secrets.NCR_REGISTRY }}/tee2
    IMAGE_TAG: ${{ secrets.NCR_REGISTRY }}/tee2:latest

jobs:

    build:
        name: Build Image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ secrets.NCR_REGISTRY }}
                username: ${{ secrets.NCR_ACCESS_KEY_ID }}
                password: ${{ secrets.NCR_SECRET_KEY }}

            - name: Get current timestamp
              id: timestamp
              run: echo "timestamp=$(date '+%s')" >> "$GITHUB_OUTPUT"

            - name: build-and-push
              uses: docker/build-push-action@v4
              with:
                context: tee2
                tags: ${{ env.IMAGE_TAG }},"${{ env.IMAGE }}:${{ steps.timestamp.outputs.timestamp }}"
                push: true

    # Pull Image From NCR / Run new container with new image
    deploy-staging:
        needs: build
        name: deploy to staging
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: pull and run image
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ secrets.HOST_STAGING }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                script: |
                    sudo apt-get update
                    sudo apt-get install docker.io
                    sudo docker login \
                    ${{ secrets.NCR_REGISTRY }} \
                     -u ${{ secrets.NCR_ACCESS_KEY_ID }} -p ${{ secrets.NCR_SECRET_KEY }}
                    sudo docker pull ${{ env.IMAGE_TAG }}
                    sudo docker stop tee2 && docker rm tee2
                    sudo docker run -p 8000:8000 -d --name tee2 \
                    -v ~/.aws:/root/.aws:ro \
                    ${{ secrets.NCR_REGISTRY }}/tee2:latest